# Información general del sitio
title: "Portfolio de Nerea"
description: "Portfolio personal de Nerea, presentando mis proyectos y habilidades."
baseurl: "" # dejar vacío si es root


# Autor
author:
  name: "Nerea Candón Ramos"
  email: "nereacandonramos@gmail.com"

# Tema minimalista elegante
theme: jekyll-theme-cayman 

# Navegación
nav:
  - title: "Sobre mí"
    url: "#sobre-mi"
  - title: "Proyectos"
    url: "#write-up"
  - title: "Contacto"
    url: "#contacto"

# Opciones de markdown
markdown: kramdown
kramdown:
  input: GFM